### ISSUE TITLE
Setup CI server

### ISSUE THREAD

**Issue by skamoen** [AreaFiftyLAN/lancie-api#63]
Travis, Jenkins, TeamCity... something.

**Comment by JeremybellEU** [comment]
Travis should be good-to-go with the configuration:
```yml
language: java
jdk:
  - oraclejdk8
```
